"""Week 7 clustering experiments for UCL player-season profiles.

This script consumes the PCA embedding generated by build_pca_feature_matrix.py
and runs documented clustering experiments:

- K-Means parameter sweep over k.
- DBSCAN density sweep over eps and min_samples.
- Validation tables, cluster labels, 2D plots, and a markdown report.

No football-specific formula is inferred here. The only computations are
standard clustering metrics from scikit-learn.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
ARTIFACTS_DIR = BASE_DIR / "artifacts"
REPORTS_DIR = BASE_DIR / "reports"

os.environ.setdefault("MPLCONFIGDIR", str(ARTIFACTS_DIR / ".matplotlib-cache"))

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import DBSCAN, KMeans
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score, silhouette_score
from sklearn.preprocessing import StandardScaler


PCA_2D_PATH = ARTIFACTS_DIR / "pca_player_season_2d.csv"
PCA_VARIANCE_PATH = ARTIFACTS_DIR / "pca_explained_variance.csv"

KMEANS_SWEEP_PATH = ARTIFACTS_DIR / "clustering_kmeans_sweep.csv"
DBSCAN_SWEEP_PATH = ARTIFACTS_DIR / "clustering_dbscan_sweep.csv"
CLUSTER_LABELS_PATH = ARTIFACTS_DIR / "player_season_cluster_labels.csv"
KMEANS_PROFILES_PATH = ARTIFACTS_DIR / "clustering_kmeans_profiles.csv"
DBSCAN_PROFILES_PATH = ARTIFACTS_DIR / "clustering_dbscan_profiles.csv"
KMEANS_PLOT_PATH = ARTIFACTS_DIR / "clustering_kmeans_2d.png"
DBSCAN_PLOT_PATH = ARTIFACTS_DIR / "clustering_dbscan_2d.png"
SILHOUETTE_PLOT_PATH = ARTIFACTS_DIR / "clustering_kmeans_silhouette.png"
REPORT_PATH = REPORTS_DIR / "clustering_validation_report.md"
JSON_REPORT_PATH = ARTIFACTS_DIR / "clustering_validation_report.json"

RANDOM_STATE = 42
K_RANGE = range(2, 11)
# silhouette_score is O(n^2); subsample for large player-season tables so the
# sweep stays tractable (the embedding can hold ~190k+ rows after the rebuild).
SILHOUETTE_SAMPLE_SIZE = 10000
# DBSCAN radius queries do not scale to ~190k dense points; cap its working set.
DBSCAN_MAX_POINTS = 20000
DBSCAN_EPS_VALUES = [0.15, 0.25, 0.35, 0.5, 0.75, 1.0, 1.25, 1.5]
DBSCAN_MIN_SAMPLES = [5, 10, 20]


def safe_silhouette(features: np.ndarray, labels: np.ndarray) -> float:
    """Silhouette with subsampling for large n; returns NaN if undefined.

    On very imbalanced clusterings a random subsample can end up with a single
    label, which silhouette_score rejects. We treat that as "not computable"
    (NaN) instead of crashing the whole sweep.
    """
    n = len(features)
    sample = min(SILHOUETTE_SAMPLE_SIZE, n) if n > SILHOUETTE_SAMPLE_SIZE else None
    try:
        return float(silhouette_score(features, labels, sample_size=sample, random_state=RANDOM_STATE))
    except ValueError:
        return float("nan")


@dataclass
class ClusteringResult:
    data: pd.DataFrame
    features_scaled: np.ndarray
    kmeans_sweep: pd.DataFrame
    dbscan_sweep: pd.DataFrame
    labels: pd.DataFrame
    kmeans_profiles: pd.DataFrame
    dbscan_profiles: pd.DataFrame
    selected_k: int
    selected_dbscan_eps: float
    selected_dbscan_min_samples: int


def load_pca_embedding() -> pd.DataFrame:
    if not PCA_2D_PATH.exists():
        raise FileNotFoundError(
            f"Missing PCA embedding: {PCA_2D_PATH}. Run python src/build_pca_feature_matrix.py first."
        )
    data = pd.read_csv(PCA_2D_PATH)
    required = {"player_id", "player_name", "season", "position_group", "PC1", "PC2"}
    missing = required - set(data.columns)
    if missing:
        raise ValueError(f"PCA embedding is missing required columns: {sorted(missing)}")
    return data.dropna(subset=["PC1", "PC2"]).reset_index(drop=True)


def scale_embedding(data: pd.DataFrame) -> np.ndarray:
    # PCA scores are numeric, but PC1 and PC2 can still have different variance.
    # Standardizing them avoids PC1 dominating Euclidean distances in clustering.
    return StandardScaler().fit_transform(data[["PC1", "PC2"]])


def valid_silhouette(features: np.ndarray, labels: np.ndarray) -> float | None:
    unique_labels = set(labels)
    if -1 in unique_labels:
        unique_labels.remove(-1)
    if len(unique_labels) < 2:
        return None
    mask = labels != -1
    if mask.sum() <= len(unique_labels):
        return None
    value = safe_silhouette(features[mask], labels[mask])
    return None if value != value else value  # NaN -> None


def run_kmeans_sweep(features: np.ndarray) -> pd.DataFrame:
    rows = []
    for k in K_RANGE:
        model = KMeans(n_clusters=k, init="k-means++", n_init=20, random_state=RANDOM_STATE)
        labels = model.fit_predict(features)
        rows.append(
            {
                "algorithm": "kmeans",
                "k": k,
                "inertia": float(model.inertia_),
                "silhouette": safe_silhouette(features, labels),
                "calinski_harabasz": float(calinski_harabasz_score(features, labels)),
                "davies_bouldin": float(davies_bouldin_score(features, labels)),
                "cluster_count": int(len(set(labels))),
                "noise_ratio": 0.0,
            }
        )
    return pd.DataFrame(rows)


def choose_kmeans_model(features: np.ndarray, sweep: pd.DataFrame) -> tuple[int, np.ndarray]:
    # Prefer the highest silhouette; if silhouette is undefined for every k
    # (extreme cluster imbalance), fall back to the Calinski-Harabasz score.
    valid = sweep[sweep["silhouette"].notna()]
    if not valid.empty:
        selected = valid.sort_values(["silhouette", "calinski_harabasz"], ascending=[False, False]).iloc[0]
    else:
        selected = sweep.sort_values("calinski_harabasz", ascending=False).iloc[0]
    k = int(selected["k"])
    model = KMeans(n_clusters=k, init="k-means++", n_init=20, random_state=RANDOM_STATE)
    labels = model.fit_predict(features)
    return k, labels


def run_dbscan_sweep(features: np.ndarray) -> pd.DataFrame:
    rows = []
    n_samples = len(features)
    for eps in DBSCAN_EPS_VALUES:
        for min_samples in DBSCAN_MIN_SAMPLES:
            model = DBSCAN(eps=eps, min_samples=min_samples)
            labels = model.fit_predict(features)
            non_noise = labels[labels != -1]
            cluster_count = len(set(non_noise))
            noise_count = int((labels == -1).sum())
            rows.append(
                {
                    "algorithm": "dbscan",
                    "eps": eps,
                    "min_samples": min_samples,
                    "cluster_count": int(cluster_count),
                    "noise_count": noise_count,
                    "noise_ratio": float(noise_count / n_samples),
                    "silhouette_non_noise": valid_silhouette(features, labels),
                    "non_noise_count": int(len(non_noise)),
                }
            )
    return pd.DataFrame(rows)


def choose_dbscan_model(features: np.ndarray, sweep: pd.DataFrame) -> tuple[float, int, np.ndarray]:
    candidates = sweep[
        sweep["silhouette_non_noise"].notna()
        & (sweep["cluster_count"] >= 2)
        & (sweep["noise_ratio"] <= 0.40)
        & (sweep["non_noise_count"] >= max(50, int(len(features) * 0.20)))
    ].copy()
    if candidates.empty:
        candidates = sweep[sweep["silhouette_non_noise"].notna()].copy()
    selected = candidates.sort_values(
        ["silhouette_non_noise", "cluster_count", "noise_ratio"],
        ascending=[False, False, True],
    ).iloc[0]
    eps = float(selected["eps"])
    min_samples = int(selected["min_samples"])
    labels = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(features)
    return eps, min_samples, labels


def cluster_profiles(data: pd.DataFrame, label_column: str) -> pd.DataFrame:
    rows = []
    for cluster_id, group in data.groupby(label_column):
        position_mix = group["position_group"].value_counts(normalize=True).head(3)
        season_mix = group["season"].value_counts(normalize=True).head(3)
        rows.append(
            {
                "cluster": cluster_id,
                "size": int(len(group)),
                "pc1_mean": float(group["PC1"].mean()),
                "pc2_mean": float(group["PC2"].mean()),
                "pc1_median": float(group["PC1"].median()),
                "pc2_median": float(group["PC2"].median()),
                "top_positions": "; ".join(f"{idx}: {val:.1%}" for idx, val in position_mix.items()),
                "top_seasons": "; ".join(f"{idx}: {val:.1%}" for idx, val in season_mix.items()),
                "example_players": "; ".join(group["player_name"].dropna().astype(str).head(5)),
            }
        )
    return pd.DataFrame(rows).sort_values("cluster")


def plot_clusters(data: pd.DataFrame, label_column: str, title: str, output_path: Path) -> None:
    plt.figure(figsize=(9, 6))
    labels = sorted(data[label_column].unique())
    cmap = plt.get_cmap("tab20")
    for i, label in enumerate(labels):
        subset = data[data[label_column] == label]
        if label == -1:
            color = "#9d9da1"
            marker = "x"
            alpha = 0.45
            name = "noise"
        else:
            color = cmap(i % 20)
            marker = "o"
            alpha = 0.75
            name = f"cluster {label}"
        plt.scatter(subset["PC1"], subset["PC2"], s=24, alpha=alpha, marker=marker, color=color, label=name)
    plt.axhline(0, color="#d0d0d0", linewidth=0.8)
    plt.axvline(0, color="#d0d0d0", linewidth=0.8)
    # Robust axis limits so a few far-out profiles do not squash the plot.
    for setter, col in ((plt.xlim, "PC1"), (plt.ylim, "PC2")):
        lo, hi = data[col].quantile(0.01), data[col].quantile(0.99)
        pad = (hi - lo) * 0.08 or 1.0
        setter(lo - pad, hi + pad)
    plt.title(title)
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.legend(loc="best", fontsize=8)
    plt.tight_layout()
    plt.savefig(output_path, dpi=160)
    plt.close()


def plot_kmeans_silhouette(sweep: pd.DataFrame) -> None:
    plt.figure(figsize=(8, 5))
    plt.plot(sweep["k"], sweep["silhouette"], marker="o")
    plt.xlabel("k")
    plt.ylabel("Silhouette score")
    plt.title("K-Means Parameter Sweep")
    plt.grid(alpha=0.25)
    plt.tight_layout()
    plt.savefig(SILHOUETTE_PLOT_PATH, dpi=160)
    plt.close()


def markdown_table(frame: pd.DataFrame, max_rows: int = 20) -> str:
    visible = frame.head(max_rows).copy()
    columns = list(visible.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for _, row in visible.iterrows():
        values = []
        for column in columns:
            value = row[column]
            if isinstance(value, float):
                values.append(f"{value:.4f}")
            else:
                values.append(str(value))
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def build_report(result: ClusteringResult) -> str:
    pca_variance = pd.read_csv(PCA_VARIANCE_PATH) if PCA_VARIANCE_PATH.exists() else pd.DataFrame()
    pc12_variance = float(pca_variance.head(2)["explained_variance_ratio"].sum()) if not pca_variance.empty else 0.0
    kmeans_selected = result.kmeans_sweep[result.kmeans_sweep["k"] == result.selected_k].iloc[0]
    dbscan_selected = result.dbscan_sweep[
        (result.dbscan_sweep["eps"] == result.selected_dbscan_eps)
        & (result.dbscan_sweep["min_samples"] == result.selected_dbscan_min_samples)
    ].iloc[0]

    return f"""# Week 7 Clustering and Validation Report

Generated at: `{datetime.now().isoformat(timespec="seconds")}`

## Objective

This report satisfies the Week 7 requirement: segment the domain and validate
whether the segmentation is meaningful. The experiments use the existing
player-season PCA embedding from `artifacts/pca_player_season_2d.csv`.

## Data and Variables Used

Unit of analysis: one player in one season.

Variables used for clustering: `PC1`, `PC2`.

Metadata used only for interpretation: `player_id`, `player_name`, `season`,
and `position_group`.

Why these variables:

- `PC1` and `PC2` are numeric latent features produced by the PCA pipeline.
- PCA already combines the original football features: minutes, goals, assists,
  shots, passes, tackles, interceptions, fouls, cards, and engineered per-90
  rates.
- Clustering on PCA coordinates reduces redundancy among correlated football
  statistics and keeps the Week 7 work tied to the Week 5 representation layer.
- `player_id` and `player_name` are identifiers, so they are not valid
  clustering features.
- `season` and `position_group` are not used to force clusters; they are used
  after clustering to interpret what each cluster represents.

No football formula is inferred in this script. The methods are standard
scikit-learn algorithms and metrics.

## Method References

- `KMeans` minimizes within-cluster sum of squares, reported as inertia:
  https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
- `DBSCAN` forms density-based clusters using `eps` and `min_samples`:
  https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html
- `silhouette_score` compares intra-cluster distance with nearest-cluster
  distance:
  https://scikit-learn.org/stable/modules/generated/sklearn.metrics.silhouette_score.html

## Preprocessing

The PCA scores are standardized with `StandardScaler` before clustering because
K-Means and DBSCAN use Euclidean distances. Even after PCA, `PC1` and `PC2` can
have different variances; without scaling, the higher-variance component would
dominate distance calculations.

Rows with missing `PC1` or `PC2` are dropped. No values are invented.

## PCA Context

PC1 + PC2 explained variance: `{pc12_variance:.4f}`.

This means the 2D clustering is interpretable and visual, but it does not
preserve all information from the full feature matrix. That limitation is
discussed in the failure analysis.

## K-Means Parameter Sweep

{markdown_table(result.kmeans_sweep)}

Selected K-Means model:

- `k`: `{result.selected_k}`
- silhouette: `{float(kmeans_selected['silhouette']):.4f}`
- inertia: `{float(kmeans_selected['inertia']):.4f}`
- Calinski-Harabasz: `{float(kmeans_selected['calinski_harabasz']):.4f}`
- Davies-Bouldin: `{float(kmeans_selected['davies_bouldin']):.4f}`

Selection rule: choose the `k` with the highest silhouette score. Inertia is
reported because it is the K-Means objective, but it always tends to decrease as
`k` increases, so it should not be used alone.

## DBSCAN Parameter Sweep

{markdown_table(result.dbscan_sweep)}

Selected DBSCAN model:

- `eps`: `{result.selected_dbscan_eps}`
- `min_samples`: `{result.selected_dbscan_min_samples}`
- clusters excluding noise: `{int(dbscan_selected['cluster_count'])}`
- noise ratio: `{float(dbscan_selected['noise_ratio']):.4f}`
- silhouette on non-noise points: `{float(dbscan_selected['silhouette_non_noise']):.4f}`

Selection rule: prefer a valid silhouette score, at least two non-noise
clusters, at least 20% of observations assigned to clusters, and noise ratio no
higher than 40%. This avoids selecting a model that looks good only because it
labels too many observations as noise.

## K-Means Cluster Profiles

{markdown_table(result.kmeans_profiles, max_rows=30)}

Interpretation: clusters with high positive PC1 generally represent
high-volume/high-involvement player-seasons because PC1 in the PCA report loads
strongly on minutes, matches, passing volume, defensive activity, and shot
volume. PC2 separates more attacking output because the PCA report shows strong
loadings for goals, shots on target, goals per 90, and shot efficiency.

## DBSCAN Cluster Profiles

{markdown_table(result.dbscan_profiles, max_rows=30)}

DBSCAN should be interpreted as a density test rather than a replacement for
K-Means. It can identify dense regions and noise/outlier player-seasons, but it
is sensitive to the `eps` scale.

## Visual Outputs

- K-Means 2D plot: `artifacts/clustering_kmeans_2d.png`
- DBSCAN 2D plot: `artifacts/clustering_dbscan_2d.png`
- K-Means silhouette sweep: `artifacts/clustering_kmeans_silhouette.png`

## Failure Analysis and Limits

- The current clustering uses only `PC1` and `PC2`. This is useful for visual
  explanation, but PC1 + PC2 do not capture 100% of the original variance.
- K-Means assumes roughly compact, spherical clusters in Euclidean space. If
  player profiles form elongated tactical gradients, K-Means may split a
  continuum into artificial groups.
- DBSCAN is sensitive to `eps`. Small `eps` values can mark too many players as
  noise, while large `eps` values can collapse most players into one cluster.
- Position labels are partly incomplete or normalized into broad groups, so
  cluster interpretation should rely on statistical profiles and examples, not
  only position names.
- The clusters describe statistical similarity, not causal player quality.

## Work Left for Teammates

- Add football interpretation for each cluster using domain examples.
- Compare this 2D PCA clustering with clustering on the full PCA component set.
- Add slides with representative players and tactical labels.
- Expand the failure analysis with manual review of unusual/outlier players.
"""


def run_clustering() -> ClusteringResult:
    data = load_pca_embedding()
    features_scaled = scale_embedding(data)
    kmeans_sweep = run_kmeans_sweep(features_scaled)
    selected_k, kmeans_labels = choose_kmeans_model(features_scaled, kmeans_sweep)

    # DBSCAN's radius_neighbors does not scale to ~190k dense points (it can OOM),
    # so the density sweep runs on a capped random subsample; rows outside the
    # subsample are left as noise (-1). DBSCAN here is a density probe, not the
    # production segmentation (K-Means provides the cluster labels used downstream).
    if len(features_scaled) > DBSCAN_MAX_POINTS:
        rng = np.random.default_rng(RANDOM_STATE)
        sub_idx = rng.choice(len(features_scaled), size=DBSCAN_MAX_POINTS, replace=False)
    else:
        sub_idx = np.arange(len(features_scaled))
    features_db = features_scaled[sub_idx]
    dbscan_sweep = run_dbscan_sweep(features_db)
    selected_eps, selected_min_samples, sub_labels = choose_dbscan_model(features_db, dbscan_sweep)
    dbscan_labels = np.full(len(features_scaled), -1, dtype="int64")
    dbscan_labels[sub_idx] = sub_labels

    labels = data.copy()
    labels["kmeans_cluster"] = kmeans_labels
    labels["dbscan_cluster"] = dbscan_labels

    return ClusteringResult(
        data=data,
        features_scaled=features_scaled,
        kmeans_sweep=kmeans_sweep,
        dbscan_sweep=dbscan_sweep,
        labels=labels,
        kmeans_profiles=cluster_profiles(labels, "kmeans_cluster"),
        dbscan_profiles=cluster_profiles(labels, "dbscan_cluster"),
        selected_k=selected_k,
        selected_dbscan_eps=selected_eps,
        selected_dbscan_min_samples=selected_min_samples,
    )


def write_outputs(result: ClusteringResult) -> None:
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    result.kmeans_sweep.to_csv(KMEANS_SWEEP_PATH, index=False, encoding="utf-8")
    result.dbscan_sweep.to_csv(DBSCAN_SWEEP_PATH, index=False, encoding="utf-8")
    result.labels.to_csv(CLUSTER_LABELS_PATH, index=False, encoding="utf-8")
    result.kmeans_profiles.to_csv(KMEANS_PROFILES_PATH, index=False, encoding="utf-8")
    result.dbscan_profiles.to_csv(DBSCAN_PROFILES_PATH, index=False, encoding="utf-8")
    plot_clusters(result.labels, "kmeans_cluster", "K-Means Clusters on PCA Player-Season Map", KMEANS_PLOT_PATH)
    plot_clusters(result.labels, "dbscan_cluster", "DBSCAN Clusters on PCA Player-Season Map", DBSCAN_PLOT_PATH)
    plot_kmeans_silhouette(result.kmeans_sweep)
    REPORT_PATH.write_text(build_report(result), encoding="utf-8")
    JSON_REPORT_PATH.write_text(
        json.dumps(
            {
                "generated_at": datetime.now().isoformat(timespec="seconds"),
                "input": str(PCA_2D_PATH),
                "rows": int(len(result.data)),
                "selected_kmeans_k": result.selected_k,
                "selected_dbscan_eps": result.selected_dbscan_eps,
                "selected_dbscan_min_samples": result.selected_dbscan_min_samples,
                "outputs": {
                    "kmeans_sweep": str(KMEANS_SWEEP_PATH),
                    "dbscan_sweep": str(DBSCAN_SWEEP_PATH),
                    "labels": str(CLUSTER_LABELS_PATH),
                    "kmeans_profiles": str(KMEANS_PROFILES_PATH),
                    "dbscan_profiles": str(DBSCAN_PROFILES_PATH),
                    "kmeans_plot": str(KMEANS_PLOT_PATH),
                    "dbscan_plot": str(DBSCAN_PLOT_PATH),
                    "silhouette_plot": str(SILHOUETTE_PLOT_PATH),
                    "report": str(REPORT_PATH),
                },
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )


def main() -> None:
    result = run_clustering()
    write_outputs(result)
    print(
        json.dumps(
            {
                "report": str(REPORT_PATH),
                "labels": str(CLUSTER_LABELS_PATH),
                "selected_kmeans_k": result.selected_k,
                "selected_dbscan_eps": result.selected_dbscan_eps,
                "selected_dbscan_min_samples": result.selected_dbscan_min_samples,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    from src.logging_utils import run_logged
    run_logged("build_clustering_analysis", main)
